name: sci_http_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  uuid:
  http:
  #  tson:
  #    path: ../../dtson
  tson:
    git:
      url: https://github.com/tercen/dtson
      ref: 1.4.1
  logging:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
